services:
  - type: web
    name: laravel-backend
    env: php
    buildCommand: composer install --no-dev
    startCommand: php -S 0.0.0.0:10000 -t public
    staticPublishPath: public
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: APP_KEY
        value: base64:+cktbCf/+/9yOHPMusrt8laOgvBuKcTIaUAnnBwKOV8=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
